azure:
  account-key:
    id: https://cert-blues-ellpjdvnj4ijs.vault.azure.net/keys/account-key
    signature-alg: RS256
  certificate-key-vault:
    url: https://cloudalni.vault.azure.net
  table-storage:
    service-url: https://certbluesellpjdvnj4ijs.table.core.windows.net
    request-table-name: requests

lets-encrypt:
  directory-url: https://acme-v02.api.letsencrypt.org/directory

spring:
  sql:
    init:
      mode: never

  application:
    name: cert-blues-test
