azure:
  account-key:
    id: https://cert-blues-dev.vault.azure.net/keys/account-key-ellpjdvnj4ijs
    signature-alg: RS256
  key-vault:
    url: https://cert-blues-dev.vault.azure.net
  table-storage:
    service-url: https://certbluesdev.table.core.windows.net
    request-table-name: requests

lets-encrypt:
  directory-url: https://acme-staging-v02.api.letsencrypt.org/directory

spring:
  sql:
    init:
      mode: never

  application:
    name: cert-blues

cert-blues:
  max-execution-time: 10m
  renewal-interval: 60d
