name: Deployment to PROD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/alexandernikiforov/cert-blues-app
          tags: |
            type=raw,value={{tag}},enable=${{ contains(github.ref, 'refs/tags/') }},priority=100
            type=raw,value={{sha}},priority=200

      - name: Deploy to TEST
        uses: azure/CLI@v1
        with:
          azcliversion: 2.37.0
          inlineScript: |
            az login --service-principal \
              -u ${{ secrets.DEPLOYMENT_AZURE_CLIENT_ID }} \
              -p ${{ secrets.DEPLOYMENT_AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}
            
            az deployment group create \
              --resource-group cert-blues-prod \
              --parameters image=${{ fromJSON(steps.meta.outputs.json).tags[0] }} \
              --template-file cert-blues-deployment/src/bicep/aci-deployment-prod.bicep
