name: Deployment to TEST

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: test

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/alexandernikiforov/cert-blues-app
          tags: |
            type=raw,value={{tag}},enable=${{ contains(github.ref, 'refs/tags/') }},priority=200
            type=ref,event=branch,priority=100

      - name: Deploy to TEST
        uses: azure/CLI@v1
        env:
          # remove environment variables set by the meta action because they are breaking the azure cli action
          DOCKER_METADATA_OUTPUT_VERSION: ""
          DOCKER_METADATA_OUTPUT_TAGS: ""
          DOCKER_METADATA_OUTPUT_LABELS: ""
          DOCKER_METADATA_OUTPUT_JSON: ""
          DOCKER_METADATA_OUTPUT_BAKE_FILE: ""
        with:
          inlineScript: |
            az login --service-principal \
              -u ${{ secrets.DEPLOYMENT_AZURE_CLIENT_ID }} \
              -p ${{ secrets.DEPLOYMENT_AZURE_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }}
            
            az deployment group create \
              --resource-group cert-blues-dev \
              --parameters image=${{ fromJSON(steps.meta.outputs.json).tags[0] }} \
              --template-file cert-blues-deployment/src/bicep/aci-deployment-test.bicep
