name: Release (Automatic)

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag for Docker Image
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/alexandernikiforov/cert-blues-app
          tags: |
            type=ref,event=branch

      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Pull and tag image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}
          docker tag \
            ${{ steps.meta.outputs.tags }} \
            ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.inputs.tag }}
          docker push ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.inputs.tag }}
