name: Release Tag (Automatic)

on:
  release:
    types:
      - published

jobs:
  tag-on-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/alexandernikiforov/cert-blues-app
          tags: |
            type=raw,value={{sha}}

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Pull and tag image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}
          docker tag \
            ${{ steps.meta.outputs.tags }} \
            ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.release.tag_name }}
          docker push ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.release.tag_name }}
