name: Release (Automatic)

on:
  release:
    types:
      - published

jobs:
  tag-on-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Use the name of the target branch to find the image
      - name: Pull and tag image
        run: |
          docker pull ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.release.target_commitish }}
          docker tag \
            ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.release.target_commitish }} \
            ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.release.tag_name }}
          docker push ghcr.io/alexandernikiforov/cert-blues-app:${{ github.event.release.tag_name }}
